name       : gmusicbrowser
version    : 1.1.16
release    : 2
source     :
    - https://github.com/squentin/gmusicbrowser/archive/v1.1.16.tar.gz : fa86235c0e39def45a061b66a92321f60eb3b054a79a0f010db101a427f2785c
license    : GPL-3.0-only
component  : multimedia.audio
summary    : Music player for large collections of music.
description: |
    Very customizable music player for large collections of files.
    Main features
    - customizable window layouts
    - artist/album lock easily restrict playlist to current artist/album
    - easy access to related songs (same artist/album/title)
    - simple mass-tagging and mass-renaming
    - support multiple genres for each song
    - customizable labels can be set for each song
    - filters with unlimited nesting of conditions
    - customizable weighted random mode
builddeps  :
    - discount
rundeps    :
    - gstreamer-1.0
    - gstreamer-1.0-plugins-base
    - gstreamer-1.0-plugins-good
    - perl-cairo
    - perl-gettext
    - perl-glib
    - perl-glib-object-introspection
    - perl-gtk2
    - perl-gtk2-appindicator
    - perl-gtk2-notify
    - perl-pango
setup      : |
    %patch -p1 < $pkgfiles/0002-set-notification-category.patch
install    : |
    %make_install
